Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/lambda/click-edge-fn"
      RetentionInDays: 5

  ClickLambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref ClickLambda
      Description: v1

  ClickLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: click-edge-fn
      Role: !GetAtt ClickLambdaRole.Arn
      Runtime: nodejs18.x
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = (event, ctx, cb) => {
            console.log(JSON.stringify(event))
            const request = event.Records[0].cf.request;
            if (request.method === 'GET') {
              const https = require('https');
              const options = {
                hostname: 'jeli.fish',
                port: 443,
                path: '/api/click',
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json'
                }
              };
              const data = JSON.stringify({
                id: request.uri,
              });
              const req = https.request(options, (res) => {
                res.on('data', (chunk) => {
                });
                res.on('end', () => {
                  console.log(`sent`)
                });
              });

              // Define the error handling for the HTTPS request
              req.on('error', (error) => {
                console.error(error);
                callback(error);
              });

              // Send the HTTPS request with the data
              req.write(data);
              req.end();
            }
            
            callback(null, request);
            return;
          }

  ClickLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
